# Generated by Django 5.1.7 on 2025-03-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_candidat",
            new_name="est_candidat",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_recruteur",
            new_name="est_recruteur",
        ),
    ]
