# Generated by Django 5.1.7 on 2025-03-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_is_candidat_user_est_candidat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidat",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="recruteur",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
