# Generated by Django 5.1.7 on 2025-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_candidature_candidat_remove_recruteur_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidature",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cvs/"),
        ),
        migrations.AddField(
            model_name="candidature",
            name="lettre_motivation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
