# Generated by Django 5.1.7 on 2025-03-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_candidature_cv_candidature_lettre_motivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="offre",
            name="date_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
