# Generated by Django 5.1.7 on 2025-03-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_offre_date_expiration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offre",
            name="date_expiration",
        ),
    ]
