# Generated by Django 5.1.7 on 2025-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_offre_date_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidature",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en attente", "En attente"),
                    ("acceptée", "Acceptée"),
                    ("refusée", "Refusée"),
                ],
                default="en attente",
                max_length=100,
            ),
        ),
    ]
